# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyAutoAli.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(359, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.OpenFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFileBtn.setObjectName("OpenFileBtn")
        self.gridLayout.addWidget(self.OpenFileBtn, 0, 0, 1, 1)
        self.OpenFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.OpenFilePath.setObjectName("OpenFilePath")
        self.gridLayout.addWidget(self.OpenFilePath, 0, 1, 1, 1)
        self.SaveFileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.SaveFileBtn.setObjectName("SaveFileBtn")
        self.gridLayout.addWidget(self.SaveFileBtn, 1, 0, 1, 1)
        self.SaveFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.SaveFilePath.setInputMask("")
        self.SaveFilePath.setText("")
        self.SaveFilePath.setObjectName("SaveFilePath")
        self.gridLayout.addWidget(self.SaveFilePath, 1, 1, 1, 1)
        self.AutoOpenCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.AutoOpenCheck.setObjectName("AutoOpenCheck")
        self.gridLayout.addWidget(self.AutoOpenCheck, 2, 0, 1, 1)
        self.LinksTxtEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LinksTxtEdit.setObjectName("LinksTxtEdit")
        self.gridLayout.addWidget(self.LinksTxtEdit, 3, 0, 1, 2)
        self.StartBtn = QtWidgets.QPushButton(self.centralwidget)
        self.StartBtn.setObjectName("StartBtn")
        self.gridLayout.addWidget(self.StartBtn, 4, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 5, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.OpenFileBtn.clicked.connect(self.OpenFileClicked()) # type: ignore
        self.SaveFileBtn.clicked.connect(self.SaveToClicked()) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def OpenFileClicked(self):
        pass

    def SaveToClicked(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyAutoAli"))
        self.OpenFileBtn.setText(_translate("MainWindow", "Open file..."))
        self.SaveFileBtn.setText(_translate("MainWindow", "Save to..."))
        self.AutoOpenCheck.setText(_translate("MainWindow", "Auto open"))
        self.LinksTxtEdit.setPlainText(_translate("MainWindow", "Here will be your links"))
        self.StartBtn.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
